rules:
- BrokenNilCheck
- CollapsibleIfStatements
- ConstantConditionalOperator
- DeadCode
- ForLoopShouldBeWhileLoop
- JumbledIncrementer
- MisplacedNullCheck
- MisplacedNilCheck
- MultipleUnaryOperator
- MissingHashMethod
- MisplacedDefaultLabel
- InvertedLogic
- MissingBreakInSwitchStatement
- NonCaseLabelInSwitchStatement
- AssignIvarOutsideAccessors
- ParameterReassignment
- AvoidPrivateStaticMembers
- EmptyElseBlock
- EmptyFinallyStatement
- EmptyForStatement
- EmptyIfStatement
- EmptySwitchStatement
- UseBoxedExpression
- UseContainerLiteral
- UseNumberLiteral
- UseObjectSubscripting
- ShortVariableName
- RedundantConditionalOperator
- RedundantIfStatement
- RedundantNilCheck
- UnnecessaryElseStatement
- UselessParentheses
- HighCyclomaticComplexity
- LongClass
- LongMethod
- DeepNestedBlock
- TooManyFields
- TooManyMethods
- TooManyParameters
- UnusedLocalVariable
- MutableObjectPropertyWithStrongAttribute
- PointerTypePropertyWithAssignAttribute

rule-configurations:
- key: LONG_LINE
  value: 200
- key: CYCLOMATIC_COMPLEXITY
  value: 10
- key: LONG_CLASS
  value: 600
- key: LONG_METHOD
  value: 50
- key: MAXIMUM_IF_LENGTH
  value: 15
- key: MINIMUM_CASES_IN_SWITCH
  value: 3
- key: NESTED_BLOCK_DEPTH
  value: 5
- key: SHORT_VARIABLE_NAME
  value: 3
- key: TOO_MANY_FIELDS
  value: 20
- key: TOO_MANY_METHODS
  value: 40
- key: TOO_MANY_PARAMETERS
  value: 10

max-priority-1: 99999
max-priority-2: 99999
max-priority-3: 99999

exclude_regex: /Pods/
report_type: json
list_enabled_rules: true
